theme: minimal-mistakes-jekyll

nome: Risav Karna

description: Developer

avatar: https://avatars1.githubusercontent.com/u/1485929?s=400&v=4

#remote_theme: "mmistakes/minimal-mistakes"

repository: risavkarna/cosys
